/**
 * Verifier: Evidence Completeness
 *
 * Checks that the evidence directory contains required artifacts.
 */

import { existsSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Verifier, VerificationResult, VerificationContext } from '../types/index.js';

export const evidenceVerifier: Verifier = {
  name: 'evidence-completeness',
  description: 'Checks that evidence directory and artifacts exist',

  async verify(ctx: VerificationContext): Promise<VerificationResult> {
    const issues: string[] = [];
    const evidence: string[] = [];

    // Check evidence directory
    const evidenceDir = resolve(ctx.repoRoot, 'evidence');
    if (!existsSync(evidenceDir)) {
      // Not a failure — evidence dir is generated by EAE
      evidence.push('evidence/ directory does not exist yet (will be created by EAE)');
    } else {
      const files = readdirSync(evidenceDir);
      evidence.push(`evidence/ contains ${files.length} files: ${files.join(', ')}`);
    }

    // Check SPIKE-01 evidence
    const spike01Evidence = resolve(ctx.repoRoot, 'spikes/SPIKE-01');
    const requiredSpikeEvidence = [
      'evidence-phase1.json',
      'trace-report.json',
      'results-run8-1h.json',
      'results-run7.json',
      'EAR-FINAL-REPORT.md',
    ];

    for (const file of requiredSpikeEvidence) {
      const path = resolve(spike01Evidence, file);
      if (existsSync(path)) {
        evidence.push(`✅ spikes/SPIKE-01/${file}`);
      } else {
        issues.push(`Missing: spikes/SPIKE-01/${file}`);
        evidence.push(`❌ spikes/SPIKE-01/${file}`);
      }
    }

    if (issues.length > 0) {
      return {
        name: this.name,
        status: 'FAIL',
        message: `${issues.length} evidence artifact(s) missing`,
        details: { issues },
        evidence,
      };
    }

    return {
      name: this.name,
      status: 'PASS',
      message: 'All required evidence artifacts present',
      evidence,
    };
  },
};
