/**
 * Unit tests for evidence-verifier.ts (B1 closure)
 *
 * Tests:
 *  1. PASSES when all required SPIKE-01 evidence artifacts exist
 *  2. FAILS when a required evidence file is missing (falsification)
 *  3. PASSES when evidence directory does not exist yet (not a failure)
 *
 * Enforcement Type: Machine-Enforceable (Rule 43)
 * Related Rule: Rule 4 (Observability First), Rule 15 (Independent Reproduction)
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { evidenceVerifier } from '../evidence-verifier.js';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const REQUIRED_SPIKE_EVIDENCE = [
  'evidence-phase1.json',
  'trace-report.json',
  'results-run8-1h.json',
  'results-run7.json',
  'EAR-FINAL-REPORT.md',
];

function createSpikeEvidence(repoDir: string): void {
  const spikeDir = join(repoDir, 'spikes', 'SPIKE-01');
  mkdirSync(spikeDir, { recursive: true });
  for (const file of REQUIRED_SPIKE_EVIDENCE) {
    writeFileSync(join(spikeDir, file), `{"sample-data": "${file}"}\n`);
  }
}

describe('evidenceVerifier', () => {
  let tmpRepo: string;

  beforeAll(() => {
    tmpRepo = mkdtempSync(join(tmpdir(), 'eae-evidence-'));
  });

  afterAll(() => {
    rmSync(tmpRepo, { recursive: true, force: true });
  });

  it('PASSES when all required SPIKE-01 evidence artifacts exist', async () => {
    rmSync(tmpRepo, { recursive: true, force: true });
    mkdirSync(tmpRepo, { recursive: true });
    createSpikeEvidence(tmpRepo);

    const result = await evidenceVerifier.verify({
      repoRoot: tmpRepo,
      evidenceDir: join(tmpRepo, 'evidence'),
    });

    expect(result.status).toBe('PASS');
    expect(result.message).toMatch(/All required evidence artifacts present/);
  });

  it('FAILS when a required evidence file is missing (falsification)', async () => {
    rmSync(tmpRepo, { recursive: true, force: true });
    mkdirSync(tmpRepo, { recursive: true });
    createSpikeEvidence(tmpRepo);

    // Remove one required file
    rmSync(join(tmpRepo, 'spikes', 'SPIKE-01', 'EAR-FINAL-REPORT.md'));

    const result = await evidenceVerifier.verify({
      repoRoot: tmpRepo,
      evidenceDir: join(tmpRepo, 'evidence'),
    });

    expect(result.status).toBe('FAIL');
    expect(result.message).toMatch(/evidence artifact\(s\) missing/);
    expect(JSON.stringify(result.details)).toMatch(/EAR-FINAL-REPORT\.md/);
  });

  it('PASSES when evidence directory does not exist yet (not a failure)', async () => {
    rmSync(tmpRepo, { recursive: true, force: true });
    mkdirSync(tmpRepo, { recursive: true });
    createSpikeEvidence(tmpRepo);
    // Note: evidence/ directory is not created — verifier should still PASS
    // because evidence dir is generated by EAE, not required to pre-exist

    const result = await evidenceVerifier.verify({
      repoRoot: tmpRepo,
      evidenceDir: join(tmpRepo, 'evidence'),
    });

    expect(result.status).toBe('PASS');
  });
});
