#!/bin/bash
set -u
REPO=/home/z/smartagentics
PASS=0; FAIL=0
check() { if eval "$2" >/dev/null 2>&1; then echo "  ✅ $1"; PASS=$((PASS+1)); else echo "  ❌ $1"; FAIL=$((FAIL+1)); fi; }
echo "═══════════════════════════════════════════════════════"
echo "SmartAgentics Bootstrap Acceptance Gate"
echo "═══════════════════════════════════════════════════════"
echo "1. Repository Structure"
check "Monorepo exists" "test -d $REPO/apps && test -d $REPO/packages"
check "package.json" "test -f $REPO/package.json"
check "turbo.json" "test -f $REPO/turbo.json"
check "tsconfig.base.json" "test -f $REPO/tsconfig.base.json"
check "pnpm-workspace.yaml" "test -f $REPO/pnpm-workspace.yaml"
echo "2. CI Pipeline"
check "CI exists" "test -f $REPO/.github/workflows/ci.yml"
echo "3. Lint Configuration"
check "ESLint config" "test -f $REPO/eslint.config.mjs"
check "eslint preset" "test -f $REPO/packages/dev-config/eslint-preset.js"
echo "4. Testing Framework"
check "vitest config" "test -f $REPO/packages/dev-config/vitest-config.ts"
check "fitness tests" "test -f $REPO/tests/fitness/architecture.fitness.ts"
echo "5. Coverage Thresholds"
check "coverage thresholds" "grep -q 'thresholds' $REPO/packages/dev-config/vitest-config.ts"
echo "6. Windows Compatibility"
check "Windows job" "grep -q 'windows-latest' $REPO/.github/workflows/ci.yml"
echo "7. Developer Experience"
check "bootstrap in README" "grep -q 'pnpm bootstrap' $REPO/README.md"
check "bootstrap script" "grep -q 'bootstrap' $REPO/package.json"
check "docker-compose" "test -f $REPO/docker-compose.yml"
echo "8. Architecture Fitness"
check "fitness functions" "grep -q 'Architecture Fitness' $REPO/tests/fitness/architecture.fitness.ts"
echo "9. Logging"
check "Logger interface" "test -f $REPO/packages/sdk/src/logger/index.ts"
check "PII fields" "grep -q 'PII_FIELDS' $REPO/packages/sdk/src/logger/index.ts"
echo "10. Health Checks"
check "errors module" "test -f $REPO/packages/sdk/src/errors/index.ts"
check "config module" "test -f $REPO/packages/sdk/src/config/index.ts"
echo "ADR Completeness"
for i in 001 002 003 004 005 006 007 008 009 010 011; do check "ADR-$i" "ls $REPO/docs/adr/ADR-$i* >/dev/null 2>&1"; done
echo "Internal Platform SDK"
check "SDK index" "test -f $REPO/packages/sdk/src/index.ts"
for mod in logger events config storage auth ai workflow notifications metrics errors; do check "$mod interface" "test -f $REPO/packages/sdk/src/$mod/index.ts"; done
echo "Event Contracts"
check "ReservationCreated" "grep -q 'ReservationCreatedPayload' $REPO/packages/sdk/src/events/index.ts"
check "GuestCheckedIn" "grep -q 'GuestCheckedInPayload' $REPO/packages/sdk/src/events/index.ts"
check "InvoiceGenerated" "grep -q 'InvoiceGeneratedPayload' $REPO/packages/sdk/src/events/index.ts"
check "RoomStatusChanged" "grep -q 'RoomStatusChangedPayload' $REPO/packages/sdk/src/events/index.ts"
check "InventoryAdjusted" "grep -q 'InventoryAdjustedPayload' $REPO/packages/sdk/src/events/index.ts"
echo "Implementation Boundary"
check "No reservations" "! test -d $REPO/apps/web/src/reservations"
check "No checkin" "! test -d $REPO/apps/web/src/checkin"
check "No billing" "! test -d $REPO/apps/web/src/billing"
check "Worker placeholder" "grep -q 'export {}' $REPO/apps/worker/src/index.ts"
echo ""
echo "═══════════════════════════════════════════════════════"
echo "RESULTS: $PASS passed, $FAIL failed"
echo "═══════════════════════════════════════════════════════"
if [ "$FAIL" -gt 0 ]; then echo "❌ GATE FAILED"; exit 1; else echo "✅ GATE PASSED"; exit 0; fi
