/**
 * Domain-to-AI Context SDK interfaces (ADR-103).
 *
 * Schema-to-Prompt Compiler + Auto-Generated Tools + MCP-compatible
 * surface. When an administrator publishes a (Layer-2 typed or Layer-3
 * dynamic) `EntityType`, the compiler (1) auto-generates six generic CRUD
 * tools (create / read / update / delete / list / search) from the
 * EntityType's JSON Schema, respecting `aiReadable` / `aiWritable` field
 * metadata (directive E23); and (2) emits a domain-context preamble
 * added to the agent's system prompt listing entity types, fields,
 * relationships, and available tools in the agent's authorized scope
 * (per ADR-083 T5). The MCP-compatible surface is Phase 2+ (Phase 1
 * ships in-process TypeScript tool handlers).
 *
 * This file contains TYPE DEFINITIONS ONLY — no implementation logic.
 */

/** Generated CRUD tool kind (per ADR-103 §4 Tool auto-generation). */
export type AutoToolKind = 'create' | 'read' | 'update' | 'delete' | 'list' | 'search';

/** Relationship cardinality (mirrors ADR-097 domain meta-model). */
export type EntityRelationshipCardinality = 'one-to-one' | 'one-to-many' | 'many-to-many';

/** AI-readable field projection used inside the prompt preamble. */
export interface EntityAIField {
  readonly name: string;
  readonly jsonSchemaType: string;
  readonly description?: string;
  readonly required: boolean;
  readonly aiReadable: boolean;
  readonly aiWritable: boolean;
  readonly enumValues?: readonly string[];
}

/** AI-readable relationship used inside the prompt preamble. */
export interface EntityAIRelationship {
  readonly name: string;
  readonly sourceEntityName: string;
  readonly sourceFieldName: string;
  readonly targetEntityName: string;
  readonly targetFieldName: string | null;
  readonly cardinality: EntityRelationshipCardinality;
}

/** AI-readable summary of a tool exposed for an EntityType. */
export interface EntityAIToolSummary {
  readonly kind: AutoToolKind;
  readonly name: string;
  readonly description: string;
  readonly inputFields: readonly string[];
  readonly outputFields: readonly string[];
}

/** Per-EntityType compiled AI context (added to the agent system prompt). */
export interface EntityAIContext {
  readonly entityTypeId: string;
  readonly domainId: string;
  readonly name: string;
  readonly displayName: string;
  readonly description: string;
  readonly fields: readonly EntityAIField[];
  readonly relationships: readonly EntityAIRelationship[];
  readonly tools: readonly EntityAIToolSummary[];
  readonly constraints: readonly string[];
  readonly promptTokenEstimate: number;
}

/** Per-domain compiled AI context — the full domain-context preamble. */
export interface DomainAIContext {
  readonly domainId: string;
  readonly tenantId: string;
  readonly entityContexts: readonly EntityAIContext[];
  readonly relationships: readonly EntityAIRelationship[];
  readonly totalTokenEstimate: number;
  readonly compiledAt: string;
  readonly schemaVersion: number;
}

/** Options for compiling a `DomainAIContext`. */
export interface DomainAIContextCompileOptions {
  readonly tenantId: string;
  readonly domainId: string;
  readonly agentId: string;
  readonly authorizedEntityTypeIds: readonly string[];
  readonly tokenBudget: number;
  readonly referencedEntityTypeIds?: readonly string[];
}

/**
 * `SchemaToPromptCompiler` — compiles `EntityType` metadata into a
 * domain-context preamble added to the agent's system prompt. Respects
 * `aiReadable` / `aiWritable` field booleans (directive E23); paginates
 * the entity list when the domain exceeds the token budget (per ADR-083
 * T4 context-window invariant).
 */
export interface SchemaToPromptCompiler {
  compileEntity(entityTypeId: string): Promise<EntityAIContext>;
  compileDomain(options: DomainAIContextCompileOptions): Promise<DomainAIContext>;
  toPromptPreamble(context: DomainAIContext): string;
}

/** Input options for `AutoToolGenerator.generate`. */
export interface AutoToolGenerateOptions {
  readonly entityTypeId: string;
  readonly domainId: string;
  readonly kinds?: readonly AutoToolKind[];
  readonly riskClass?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

/** A generated CRUD tool definition (OpenAI-compatible function-calling JSON Schema). */
export interface AutoGeneratedTool {
  readonly name: string;
  readonly kind: AutoToolKind;
  readonly entityTypeId: string;
  readonly domainId: string;
  readonly description: string;
  readonly inputSchema: Readonly<Record<string, unknown>>;
  readonly outputSchema: Readonly<Record<string, unknown>>;
  readonly handlerModule: string;
  readonly handlerFunction: string;
  readonly riskClass: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

/**
 * `AutoToolGenerator` — generates the six generic CRUD tools (create /
 * read / update / delete / list / search) from an `EntityType`'s JSON
 * Schema per ADR-103 §4. The handler is a generic `GenericEntityTool`
 * parameterized by `(entityTypeId, operation)` — no per-entity
 * TypeScript code. Registered into the `ToolRegistry` (ADR-054) at
 * EntityType-publish time.
 */
export interface AutoToolGenerator {
  generate(options: AutoToolGenerateOptions): Promise<readonly AutoGeneratedTool[]>;
  generateForDomain(domainId: string): Promise<readonly AutoGeneratedTool[]>;
}
